[package]
name = "xdg-shark"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version =  "4.2.5", features = ["derive", "deprecated"] }
async-std = { version = "1.12.0", features = ["attributes"] }
serde_json = "1.0.96"
glob = "0.3.0"
shellexpand = "3.1.0"
