name: Benchmark -- xdg-ninja compared to xdg-shark

on:
    workflow_dispatch:
    push:
        branches:
            - master
        
jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout xdg-shark repository
              uses: actions/checkout@v2
              
            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true
                
            - name: Checkout Bash repository
              uses: actions/checkout@v2
              with:
                  repository: 'b3nj5m1n/xdg-ninja'
                  path: 'xdg-ninja-repo'
                
                
            - name: Build rust binary
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  arg: --release
                  
            - name: Run benchmarks
              run: |
                BASH_PROGRAM="./xdg-ninja-repo/xdg-ninja.sh"
                RUST_PROGRAM="./target/release/xdg-shark"

                echo "Benchmarking Bash program:"
                sudo perf stat -r 5 -e task-clock $BASH_PROGRAM || echo "Bash program exited with code: $?"
                
                cd $GITHUB_WORKSPACE
                
                echo "Benchmarking Rust program:"
                sudo perf stat -r 5 -e task-clock $RUST_PROGRAM || echo "Bash program exited with code: $?"

