name: Benchmark -- benchmark xdg-ninja

on:
    workflow_dispatch:
    repository_dispatch:
        types: [external-repo-changed]

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout xdg-shark
              uses: actions/checkout@v2
              with:
                  repository: 'b3nj5m1n/xdg-ninja'
                  path: 'xdg-ninja-repo'
                
            - name: Run benchmarks
              run: |
                xdg_ninja_script="./xdg-ninja-repo/xdg-ninja.sh"

                benchmark_output=$(sudo perf stat -r 50 -e task-clock $xdg_ninja_script)
                echo "$benchmark_output"                
                
